//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentSlot
    {
        public AppointmentSlot()
        {
            this.AppointmentSlotConfigs = new HashSet<AppointmentSlotConfig>();
            this.AppointmentSlotPatterns = new HashSet<AppointmentSlotPattern>();
        }
    
        public int SlotId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsRepeat { get; set; }
        public Nullable<int> MinDuration { get; set; }
        public Nullable<int> SlotType { get; set; }
        public Nullable<int> GymId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> TotalDuaration { get; set; }
        public Nullable<int> UsedDuration { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual GymList GymList { get; set; }
        public virtual ICollection<AppointmentSlotConfig> AppointmentSlotConfigs { get; set; }
        public virtual ICollection<AppointmentSlotPattern> AppointmentSlotPatterns { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
