//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentBill
    {
        public int BillId { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
    
        public virtual BookAppointment BookAppointment { get; set; }
    }
}
