//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentSlotPattern
    {
        public int PatternId { get; set; }
        public Nullable<int> SlotId { get; set; }
        public string Pattern { get; set; }
        public Nullable<int> SlotDuration { get; set; }
    
        public virtual AppointmentSlot AppointmentSlot { get; set; }
    }
}
