//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAppointment
    {
        public BookAppointment()
        {
            this.AppointmentBills = new HashSet<AppointmentBill>();
        }
    
        public int BookingId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> ConfigId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsRepatable { get; set; }
        public string Pattern { get; set; }
        public Nullable<int> MeetingDuration { get; set; }
        public Nullable<int> GymId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> AppSlotId { get; set; }
        public Nullable<bool> IsBillsDeleted { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual ICollection<AppointmentBill> AppointmentBills { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual GymList GymList { get; set; }
        public virtual MemberInfo MemberInfo { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
