//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.Appointments = new HashSet<Appointment>();
            this.AppointmentSlots = new HashSet<AppointmentSlot>();
            this.BookAppointments = new HashSet<BookAppointment>();
            this.Categories = new HashSet<Category>();
            this.Classes = new HashSet<Class>();
            this.ClassTimings = new HashSet<ClassTiming>();
            this.DeletAppointmentSlots = new HashSet<DeletAppointmentSlot>();
            this.DietPlanNames = new HashSet<DietPlanName>();
            this.Enquiries = new HashSet<Enquiry>();
            this.Events = new HashSet<Event>();
            this.Expenses = new HashSet<Expens>();
            this.ExpensesTypes = new HashSet<ExpensesType>();
            this.GymAmenities = new HashSet<GymAmenity>();
            this.GymEquipments = new HashSet<GymEquipment>();
            this.GymPackages = new HashSet<GymPackage>();
            this.GymServiceLists = new HashSet<GymServiceList>();
            this.MealTimes = new HashSet<MealTime>();
            this.MembershipOffers = new HashSet<MembershipOffer>();
            this.MemberTimeSheets = new HashSet<MemberTimeSheet>();
            this.Products = new HashSet<Product>();
            this.PurchaseOrderHeaders = new HashSet<PurchaseOrderHeader>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.Schedulers = new HashSet<Scheduler>();
            this.SelectedPackages = new HashSet<SelectedPackage>();
            this.StaffBranches = new HashSet<StaffBranch>();
            this.Stocks = new HashSet<Stock>();
            this.Suppliers = new HashSet<Supplier>();
            this.Tasks = new HashSet<Task>();
            this.Workouts = new HashSet<Workout>();
            this.WorkoutPlanNames = new HashSet<WorkoutPlanName>();
        }
    
        public int BranchId { get; set; }
        public string Branchcode { get; set; }
        public string BranchName { get; set; }
        public string BranchAdress { get; set; }
        public Nullable<long> PhoneNo { get; set; }
        public string City { get; set; }
        public string BranchState { get; set; }
        public Nullable<int> GymId { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<AppointmentSlot> AppointmentSlots { get; set; }
        public virtual ICollection<BookAppointment> BookAppointments { get; set; }
        public virtual GymList GymList { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<ClassTiming> ClassTimings { get; set; }
        public virtual ICollection<DeletAppointmentSlot> DeletAppointmentSlots { get; set; }
        public virtual ICollection<DietPlanName> DietPlanNames { get; set; }
        public virtual ICollection<Enquiry> Enquiries { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Expens> Expenses { get; set; }
        public virtual ICollection<ExpensesType> ExpensesTypes { get; set; }
        public virtual ICollection<GymAmenity> GymAmenities { get; set; }
        public virtual ICollection<GymEquipment> GymEquipments { get; set; }
        public virtual ICollection<GymPackage> GymPackages { get; set; }
        public virtual ICollection<GymServiceList> GymServiceLists { get; set; }
        public virtual ICollection<MealTime> MealTimes { get; set; }
        public virtual ICollection<MembershipOffer> MembershipOffers { get; set; }
        public virtual ICollection<MemberTimeSheet> MemberTimeSheets { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<PurchaseOrderHeader> PurchaseOrderHeaders { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<Scheduler> Schedulers { get; set; }
        public virtual ICollection<SelectedPackage> SelectedPackages { get; set; }
        public virtual ICollection<StaffBranch> StaffBranches { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Workout> Workouts { get; set; }
        public virtual ICollection<WorkoutPlanName> WorkoutPlanNames { get; set; }
    }
}
