//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarInstructor
    {
        public int CalendarId { get; set; }
        public Nullable<int> TimeId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<System.DateTime> CalendarDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsClass { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
