//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.ClassTimings = new HashSet<ClassTiming>();
        }
    
        public int ClassId { get; set; }
        public string ClassName { get; set; }
        public string Description { get; set; }
        public Nullable<int> AttendenceLimit { get; set; }
        public Nullable<int> ReservationLimit { get; set; }
        public Nullable<int> DropInType { get; set; }
        public Nullable<decimal> DropInRate { get; set; }
        public string CalendarColor { get; set; }
        public Nullable<int> GymId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual GymList GymList { get; set; }
        public virtual ICollection<ClassTiming> ClassTimings { get; set; }
    }
}
