//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassTiming
    {
        public int TimingId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<bool> IsRepeats { get; set; }
        public Nullable<int> Every { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string Pattern { get; set; }
        public Nullable<int> Duration { get; set; }
        public string DayNames { get; set; }
        public string DayVals { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> GymId { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Class Class { get; set; }
        public virtual GymList GymList { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
