//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DietPlanName
    {
        public DietPlanName()
        {
            this.Diets = new HashSet<Diet>();
            this.MemberDietPlans = new HashSet<MemberDietPlan>();
        }
    
        public int DietPlanId { get; set; }
        public string DietPlanName1 { get; set; }
        public Nullable<int> GymId { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<Diet> Diets { get; set; }
        public virtual GymList GymList { get; set; }
        public virtual ICollection<MemberDietPlan> MemberDietPlans { get; set; }
    }
}
