//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enquiry
    {
        public Enquiry()
        {
            this.Followups = new HashSet<Followup>();
        }
    
        public int EnquiryId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<long> MobileNumber { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> EnquiryDate { get; set; }
        public string EmailId { get; set; }
        public Nullable<long> PhoneNumberResidence { get; set; }
        public Nullable<long> PhoneNumberOffice { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public Nullable<int> Age { get; set; }
        public string Intention { get; set; }
        public string ProgramSuggested { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> AmountOffered { get; set; }
        public string TrailOffered { get; set; }
        public Nullable<System.DateTime> TrailDate { get; set; }
        public string HowDidYouKnow { get; set; }
        public string RecievedBy { get; set; }
        public string Notes { get; set; }
        public string SMS { get; set; }
        public string call { get; set; }
        public string Email { get; set; }
        public Nullable<int> GymId { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual GymList GymList { get; set; }
        public virtual ICollection<Followup> Followups { get; set; }
    }
}
