//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Followup
    {
        public int FollowupId { get; set; }
        public Nullable<System.DateTime> LastFollowUpDate { get; set; }
        public Nullable<System.DateTime> NextFollowUpDate { get; set; }
        public string EnqStatus { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string Description { get; set; }
        public Nullable<int> EnquiryId { get; set; }
    
        public virtual Enquiry Enquiry { get; set; }
    }
}
