//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GymImage
    {
        public int GymImageId { get; set; }
        public string ImageData { get; set; }
        public Nullable<int> GymId { get; set; }
    
        public virtual GymList GymList { get; set; }
    }
}
