//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GymPackage
    {
        public GymPackage()
        {
            this.GymPayments = new HashSet<GymPayment>();
        }
    
        public int PackageId { get; set; }
        public string PackageType { get; set; }
        public Nullable<decimal> PackageAmount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Note { get; set; }
        public string GymStatus { get; set; }
        public Nullable<int> GymId { get; set; }
        public Nullable<int> Months { get; set; }
        public string Status { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual GymList GymList { get; set; }
        public virtual ICollection<GymPayment> GymPayments { get; set; }
    }
}
