//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JustbokEntities : DbContext
    {
        public JustbokEntities()
            : base("name=JustbokEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amenity> Amenities { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<AppointmentBill> AppointmentBills { get; set; }
        public virtual DbSet<AppointmentSlab> AppointmentSlabs { get; set; }
        public virtual DbSet<AppointmentSlot> AppointmentSlots { get; set; }
        public virtual DbSet<AppointmentSlotConfig> AppointmentSlotConfigs { get; set; }
        public virtual DbSet<AppointmentSlotPattern> AppointmentSlotPatterns { get; set; }
        public virtual DbSet<AppointmentStaff> AppointmentStaffs { get; set; }
        public virtual DbSet<BookAppointment> BookAppointments { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<CalendarInstructor> CalendarInstructors { get; set; }
        public virtual DbSet<CalendarMember> CalendarMembers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassTiming> ClassTimings { get; set; }
        public virtual DbSet<DeletAppointmentSlot> DeletAppointmentSlots { get; set; }
        public virtual DbSet<Diet> Diets { get; set; }
        public virtual DbSet<DietPlanName> DietPlanNames { get; set; }
        public virtual DbSet<Enquiry> Enquiries { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<ExpenseMode> ExpenseModes { get; set; }
        public virtual DbSet<Expens> Expenses { get; set; }
        public virtual DbSet<ExpensesType> ExpensesTypes { get; set; }
        public virtual DbSet<Followup> Followups { get; set; }
        public virtual DbSet<GymAdmin> GymAdmins { get; set; }
        public virtual DbSet<GymAllPackage> GymAllPackages { get; set; }
        public virtual DbSet<GymAmenity> GymAmenities { get; set; }
        public virtual DbSet<GymEquipment> GymEquipments { get; set; }
        public virtual DbSet<GymImage> GymImages { get; set; }
        public virtual DbSet<GymList> GymLists { get; set; }
        public virtual DbSet<GymLogin> GymLogins { get; set; }
        public virtual DbSet<GymPackage> GymPackages { get; set; }
        public virtual DbSet<GymPayment> GymPayments { get; set; }
        public virtual DbSet<GymServiceList> GymServiceLists { get; set; }
        public virtual DbSet<MealTime> MealTimes { get; set; }
        public virtual DbSet<Measurement> Measurements { get; set; }
        public virtual DbSet<MemberDietPlan> MemberDietPlans { get; set; }
        public virtual DbSet<MemberFreeze> MemberFreezes { get; set; }
        public virtual DbSet<MemberImage> MemberImages { get; set; }
        public virtual DbSet<MemberInfo> MemberInfoes { get; set; }
        public virtual DbSet<MemberShip> MemberShips { get; set; }
        public virtual DbSet<MembershipOffer> MembershipOffers { get; set; }
        public virtual DbSet<MemberTimeSheet> MemberTimeSheets { get; set; }
        public virtual DbSet<MemberWorkoutPlan> MemberWorkoutPlans { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual DbSet<PurchaseOrderHeader> PurchaseOrderHeaders { get; set; }
        public virtual DbSet<Scheduler> Schedulers { get; set; }
        public virtual DbSet<SelectedPackage> SelectedPackages { get; set; }
        public virtual DbSet<ShiftType> ShiftTypes { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<StaffBranch> StaffBranches { get; set; }
        public virtual DbSet<StaffLogin> StaffLogins { get; set; }
        public virtual DbSet<StaffShift> StaffShifts { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TaxType> TaxTypes { get; set; }
        public virtual DbSet<TrainerDetail> TrainerDetails { get; set; }
        public virtual DbSet<Tranfer> Tranfers { get; set; }
        public virtual DbSet<Workout> Workouts { get; set; }
        public virtual DbSet<WorkoutPlan> WorkoutPlans { get; set; }
        public virtual DbSet<WorkoutPlanName> WorkoutPlanNames { get; set; }
        public virtual DbSet<DailyTaskList> DailyTaskLists { get; set; }
        public virtual DbSet<LeaveType> LeaveTypes { get; set; }
        public virtual DbSet<StaffAbsentDetail> StaffAbsentDetails { get; set; }
        public virtual DbSet<TimeSheet> TimeSheets { get; set; }
        public virtual DbSet<StaffPresentDetail> StaffPresentDetails { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<SMSHistory> SMSHistories { get; set; }
    }
}
