//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public int MeasurementId { get; set; }
        public Nullable<System.DateTime> MeasurementDate { get; set; }
        public Nullable<System.DateTime> NextMeasurementDate { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> UpperArm { get; set; }
        public Nullable<decimal> ForeArm { get; set; }
        public Nullable<decimal> Calves { get; set; }
        public Nullable<decimal> BMI { get; set; }
        public Nullable<decimal> VFat { get; set; }
        public Nullable<decimal> Shoulder { get; set; }
        public Nullable<decimal> Chest { get; set; }
        public Nullable<decimal> Arms { get; set; }
        public Nullable<decimal> UpperABS { get; set; }
        public Nullable<decimal> WaistABS { get; set; }
        public Nullable<decimal> LowerABS { get; set; }
        public Nullable<decimal> Glutes { get; set; }
        public Nullable<decimal> Thighs { get; set; }
        public Nullable<int> MemberID { get; set; }
    
        public virtual MemberInfo MemberInfo { get; set; }
    }
}
