//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberShip
    {
        public MemberShip()
        {
            this.MemberFreezes = new HashSet<MemberFreeze>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int MembershipId { get; set; }
        public string MembershipType { get; set; }
        public Nullable<int> Months { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public Nullable<int> MemberID { get; set; }
    
        public virtual ICollection<MemberFreeze> MemberFreezes { get; set; }
        public virtual MemberInfo MemberInfo { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
