//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipOffer
    {
        public int MembershipOfferId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Months { get; set; }
        public string OfferName { get; set; }
        public Nullable<decimal> MinimumAmount { get; set; }
        public string Category { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> GymId { get; set; }
        public Nullable<int> AppLen { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual GymList GymList { get; set; }
    }
}
