//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberInfo
    {
        public MemberInfo()
        {
            this.BookAppointments = new HashSet<BookAppointment>();
            this.CalendarMembers = new HashSet<CalendarMember>();
            this.Measurements = new HashSet<Measurement>();
            this.MemberDietPlans = new HashSet<MemberDietPlan>();
            this.MemberImages = new HashSet<MemberImage>();
            this.MemberShips = new HashSet<MemberShip>();
            this.MemberTimeSheets = new HashSet<MemberTimeSheet>();
            this.MemberWorkoutPlans = new HashSet<MemberWorkoutPlan>();
            this.Payments = new HashSet<Payment>();
            this.Schedulers = new HashSet<Scheduler>();
            this.Tranfers = new HashSet<Tranfer>();
            this.Tranfers1 = new HashSet<Tranfer>();
        }
    
        public int MemberID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public Nullable<long> MobileNumber { get; set; }
        public string MemberAddress { get; set; }
        public Nullable<System.DateTime> EnrollDate { get; set; }
        public string Married { get; set; }
        public string SpouseName { get; set; }
        public Nullable<System.DateTime> SpouseBirthDate { get; set; }
        public Nullable<System.DateTime> AnniversaryDate { get; set; }
        public string Occupation { get; set; }
        public string Designation { get; set; }
        public string MemberSource { get; set; }
        public Nullable<long> PhoneResidence { get; set; }
        public Nullable<long> PhoneOffice { get; set; }
        public string ReferredBy { get; set; }
        public string Programme { get; set; }
        public string Representative { get; set; }
        public Nullable<int> GymId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> MemberReference { get; set; }
    
        public virtual ICollection<BookAppointment> BookAppointments { get; set; }
        public virtual ICollection<CalendarMember> CalendarMembers { get; set; }
        public virtual GymList GymList { get; set; }
        public virtual ICollection<Measurement> Measurements { get; set; }
        public virtual ICollection<MemberDietPlan> MemberDietPlans { get; set; }
        public virtual ICollection<MemberImage> MemberImages { get; set; }
        public virtual ICollection<MemberShip> MemberShips { get; set; }
        public virtual ICollection<MemberTimeSheet> MemberTimeSheets { get; set; }
        public virtual ICollection<MemberWorkoutPlan> MemberWorkoutPlans { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Scheduler> Schedulers { get; set; }
        public virtual ICollection<Tranfer> Tranfers { get; set; }
        public virtual ICollection<Tranfer> Tranfers1 { get; set; }
    }
}
