//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int RecieptNumber { get; set; }
        public string PaymentType { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public Nullable<long> ReferenceNumber { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> MembershipId { get; set; }
    
        public virtual MemberInfo MemberInfo { get; set; }
        public virtual MemberShip MemberShip { get; set; }
    }
}
