//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scheduler
    {
        public int SchedulerId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Repeatable { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> GymId { get; set; }
        public Nullable<int> SelectType { get; set; }
        public string SelectedDay { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual GymList GymList { get; set; }
        public virtual MemberInfo MemberInfo { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
