//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftType
    {
        public ShiftType()
        {
            this.StaffShifts = new HashSet<StaffShift>();
        }
    
        public int ShiftId { get; set; }
        public string ShiftName { get; set; }
    
        public virtual ICollection<StaffShift> StaffShifts { get; set; }
    }
}
