//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSHistory
    {
        public int SMSId { get; set; }
        public Nullable<System.DateTime> SMSDate { get; set; }
        public string SMSMessage { get; set; }
        public Nullable<long> PhoneNumber { get; set; }
        public Nullable<int> GymId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> MemberId { get; set; }
    }
}
