//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffPresentDetail
    {
        public int PresentId { get; set; }
        public string StaffInTime { get; set; }
        public string StaffOutTime { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<int> StaffId { get; set; }
    }
}
