//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffAbsentDetail
    {
        public long AbsentId { get; set; }
        public string LeaveType { get; set; }
        public Nullable<int> LeaveId { get; set; }
        public string Reason { get; set; }
        public Nullable<int> StaffId { get; set; }
    }
}
