//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffShift
    {
        public int StaffShiftId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<bool> Enable { get; set; }
    
        public virtual ShiftType ShiftType { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
