//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxType
    {
        public TaxType()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int TaxTypeId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
