//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerDetail
    {
        public int Trainerid { get; set; }
        public string ImageData { get; set; }
        public Nullable<int> Experience { get; set; }
        public string Qulifiaction { get; set; }
        public string TrainerDescription { get; set; }
        public Nullable<int> StaffId { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
