//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justbok.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tranfer
    {
        public int TransferId { get; set; }
        public Nullable<int> TransferFrom { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string MembershipType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> TransferTo { get; set; }
    
        public virtual MemberInfo MemberInfo { get; set; }
        public virtual MemberInfo MemberInfo1 { get; set; }
    }
}
